baseURL = "https://thomaspaulin.me"
languageCode = "en-nz"
title = "thomaspaulin.me"
description = "The intersection of aerospace, science, and programming."
theme = "candy"

enableRobotsTXT = true

[params]
  AuthorName = "Thomas Paulin"
  description = "The intersection of aerospace, science, and programming."

[permalinks]
  posts = "/:year/:month/:slug/"

[[menu.main]]
  name = "Posts"
  identifier = "posts"
  url = "/posts/"
  weight = 1

[[menu.main]]
  name = "Projects"
  identifier = "github"
  url = "https://github.com/thomaspaulin"
  weight = 2

[[menu.main]]
  name = "My Impossible List"
  identifier = "impossible"
  url = "/2018/04/the-impossible-list/"
  weight = 3

[[menu.main]]
  name = "About Me"
  identifier = "about"
  url = "/about/"
  weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      footnote = true
      strikethrough = true
      typographer = true