baseURL = "https://blog.thomaspaulin.me"
languageCode = "en-nz"
title = "blog.thomaspaulin.me"
description = "The writings of Thomas Paulin, a software engineer and aspiring polymath."
theme = "tpnz"

[params]
  AuthorName = "Thomas Paulin"
  description = "The writings of Thomas Paulin, a software engineer and aspiring polymath."

[permalinks]
  posts = "/:year/:month/:slug/"

[[menu.main]]
  name = "Home"
  identifier = "Home"
  url = "https://thomaspaulin.me/"
  weight = 1

[[menu.main]]
  name = "Posts"
  identifier = "Posts"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "Projects"
  identifier = "Github"
  url = "https://github.com/thomaspaulin"
  weight = 3

[[menu.main]]
  name = "My Impossible List"
  identifier = "Impossible List"
  url = "https://blog.thomaspaulin.me/2018/04/the-impossible-list/"
  weight = 4
