baseURL = "https://blog.thomaspaulin.me"
languageCode = "en-us"
title = "blog.thomaspaulin.me"
description = "A thing"
theme = "candy"

[params]
  AuthorName = "Thomas Paulin"
  description = "A thing"

[permalinks]
  posts = "/:year/:month/:slug/"

[[menu.main]]
  name = "Posts"
  identifier = "Posts"
  url = "/posts/"
  weight = 1

[[menu.main]]
  name = "Wiki"
  identifier = "Wiki"
  url = "https://wiki.thomaspaulin.me/"
  weight = 2
